image: docker:stable

stages:
  - test
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"

test:debug:
  stage: test
  image: rust:1.35.0
  script:
    - cargo test --all

build:
  stage: build
  variables:
    REGISTRY_PATH: registry.gitlab.com/lucas_pl/backupd
  only:
    refs:
      - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t ${REGISTRY_PATH}:latest .
    - docker push ${REGISTRY_PATH}:latest
