image: docker:stable

stage:
  - base

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

base-client:
  stage: base
  variables:
    REGISTRY_PATH: registry.gitlab.com/lucas_pl/backupd/client
  only:
    refs:
      - master
  script:
    - docker build -t ${REGISTRY_PATH}:latest client/
    - docker push ${REGISTRY_PATH}:latest

base-server:
  stage: base
  variables:
    REGISTRY_PATH: registry.gitlab.com/lucas_pl/backupd/server
  only:
    refs:
      - master
  script:
    - docker build -t ${REGISTRY_PATH}:latest server/
    - docker push ${REGISTRY_PATH}:latest
