[package]
name = "backupd"
version = "0.0.1"
authors = ["Lucas Salibian <lucas.salibian@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "0.13.7"

openssl = "^0.10.23"
rand = "^0.6.5"

[workspace]
members = ["./server/", "./client/"]
