[package]
name = "server"
version = "0.0.1"
authors = ["Lucas Salibian <lucas.salibian@gmail.com>"]
edition = "2018"
workspace = "../"

[dependencies]
openssl = "^0.10.23"
backupd = { path = "../" }
log = "^0.4.6"
env_logger = "^0.6.1"
