[package]
name = "agent"
version = "0.0.1"
authors = ["Lucas Salibian <lucas.salibian@gmail.com>"]
edition = "2018"
workspace = "../"

[dependencies]
backupd = { path = "../" }
log = "^0.4.6"
bincode = "^1.1.4"
env_logger = "^0.6.1"
